[CONFIG]
mode = M3
malware_path = ./samples/malware/
model = bbdnn
target_path = ./samples/target/b85a5bde791772370ab1556f21535100020bb4c47a3301cb63ec02adb77a5eac
output_folder = ./samples/output/
n_steps = 100
patience = 50
lr = 0.1


[BOXPLOT_SINGLE]
report_path = ./reports/m1.csv


[BOXPLOT_MULTIPLE]
m1_report_path = ./reports/m1.csv
m2_report_path = ./reports/m2.csv
m3_report_path = ./reports/m3.csv


[VIRUSTOTAL]
api_key = vtapikey
src = ./samples/output/
