[CONFIG]
mode = M3
malware_path = ./samples/malware/
target_path = ./samples/target/9b4be0579d79457e71ef92bf0d8a8ac0870e1867141133a16762249bb7741116
output_folder = ./samples/output/
n_steps = 100
patience = 50
lr = 0.1


[BOXPLOT_SINGLE]
report_path = ./reports/m1.csv


[BOXPLOT_MULTIPLE]
m1_report_path = ./reports/m1.csv
m2_report_path = ./reports/m2.csv
m3_report_path = ./reports/m3.csv


[VIRUSTOTAL]
api_key = vtapikey
src = ./samples/output/
